# Generated by Django 5.2.4 on 2025-07-15 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='organization',
        ),
    ]
