version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: smart_mcq_postgres
    environment:
      POSTGRES_DB: smart_mcq_db
      POSTGRES_USER: mcq_user
      POSTGRES_PASSWORD: mcq_secure_password_2024
    ports:
      - "5433:5432"  # Using port 5433 to avoid conflicts
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mcq_user -d smart_mcq_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local