# Local deployment for testing/friends
version: '3.8'

services:
  smart-mcq:
    build: .
    container_name: smart_mcq_local
    ports:
      - "8080:80"
    environment:
      - SECRET_KEY=local-demo-secret-key-12345
      - DB_NAME=smart_mcq_db
      - DB_USER=mcq_user
      - DB_PASSWORD=mcq_secure_password_2024
      - DB_HOST=localhost
      - DB_PORT=5432
    volumes:
      - mcq_data_local:/var/lib/postgresql/15/main
      - mcq_media_local:/app/media
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  mcq_data_local:
    driver: local
  mcq_media_local:
    driver: local