# Production Docker Compose for Smart MCQ Platform
version: '3.8'

services:
  smart-mcq:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: smart_mcq_production
    ports:
      - "80:80"
    environment:
      - SECRET_KEY=${SECRET_KEY:-production-secret-key-change-me-12345}
      - DB_NAME=${DB_NAME:-smart_mcq_db}
      - DB_USER=${DB_USER:-mcq_user}
      - DB_PASSWORD=${DB_PASSWORD:-mcq_secure_password_2024}
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-5432}
    volumes:
      - mcq_media:/app/media
      - mcq_logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  mcq_media:
    driver: local
  mcq_logs:
    driver: local