# Generated by Django 5.2.4 on 2025-07-12 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_sessions', '0003_testattempt_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='released_by',
            field=models.ForeignKey(blank=True, help_text='Teacher who released the results', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='result_released_at',
            field=models.DateTimeField(blank=True, help_text='When results were released to this student', null=True),
        ),
    ]
