# Generated by Django 5.2.4 on 2025-07-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_sessions', '0004_testattempt_released_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='session_name',
            field=models.CharField(blank=True, help_text="Custom name for this session (e.g., 'Math Quiz - Class 10A')", max_length=200),
        ),
    ]
