# Generated by Django 5.2.4 on 2025-07-15 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('questions', '0002_remove_question_organization'),
        ('tests', '0004_remove_test_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
