# Generated by Django 5.2.4 on 2025-07-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='answer_visibility_level',
            field=models.CharField(choices=[('score_only', 'Score Only (basic score and percentage)'), ('with_answers', 'Results with Answers (show correct vs student answers)'), ('enhanced_review', 'Enhanced Review (full detailed breakdown)')], default='with_answers', help_text='Controls what students see in their results', max_length=20),
        ),
        migrations.AddField(
            model_name='test',
            name='is_practice_test',
            field=models.BooleanField(default=True, help_text='Practice tests auto-release, assessments require manual review'),
        ),
        migrations.AddField(
            model_name='test',
            name='result_release_mode',
            field=models.CharField(choices=[('immediate', 'Immediate (auto-release on completion)'), ('manual', 'Manual (teacher controls release)'), ('scheduled', 'Scheduled (release at specific time)'), ('after_all_complete', 'After All Complete (wait for all students)')], default='immediate', help_text='Controls when results are released to students', max_length=20),
        ),
        migrations.AddField(
            model_name='test',
            name='scheduled_release_time',
            field=models.DateTimeField(blank=True, help_text='When to automatically release results (for scheduled mode)', null=True),
        ),
    ]
