# Generated by Django 5.2.4 on 2025-07-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_test_answer_visibility_level_test_is_practice_test_and_more'),
    ]

    operations = [
        # Remove the old show_results_immediately field if it exists
        migrations.RunSQL(
            "ALTER TABLE tests_test DROP COLUMN IF EXISTS show_results_immediately;",
            reverse_sql="-- No reverse operation needed"
        ),
    ]
