# Generated by Django 5.2.4 on 2025-07-15 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20250712_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='organization',
        ),
    ]
